TrajectoryPlannerROS:
  max_vel_x: 0.26
  min_vel_x: 0.2145
  max_vel_theta: 1.7
  min_in_place_vel_theta: 1.457

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  escape_vel: -0.04

  #http://wiki.ros.org/base_local_planner lots of parameters

  holonomic_robot: true